name: Publish MkDocs
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: you know material for mkdocs wasnt safe from my powershell
        shell: pwsh
        run: |
          $env:YES_MAKE_TONS_OF_FOLDERS=1
          ./redirector.ps1
          ./buildMap.ps1

      - name: Build
        run: |
          pip install -r requirements.txt
          mkdocs build -f mkdocs.github.yml
          npm ci
          npm exec -- jampack --nocache ./site
          rm -rf node_modules _jampack .cache
          
      - name: Deploy
        run: |
          mkdocs gh-deploy --force -f mkdocs.github.yml --dirty
